"""
The bundled default report template, built in code.

Built from python-docx's own default document rather than committed as a
binary so there is no ``datas`` entry for the desktop spec to forget and no
opaque file in review. Increment 2 lets the user drop in their own ``.docx``;
the writer treats this one exactly like a user template (open, keep the
section properties and footer, replace the body).
"""
from __future__ import annotations

from docx import Document
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

DISCLOSURE_STYLE = "Disclosure"
CAPTION_STYLE = "Report Caption"

_INK_MUTED = RGBColor(0x52, 0x51, 0x4E)


def _ensure_paragraph_style(doc, name: str, *, base: str = "Normal",
                            italic: bool = False, size_pt: float | None = None,
                            color: RGBColor | None = None,
                            align_center: bool = False):
    styles = doc.styles
    try:
        return styles[name]
    except KeyError:
        pass
    style = styles.add_style(name, WD_STYLE_TYPE.PARAGRAPH)
    style.base_style = styles[base]
    style.font.italic = italic
    if size_pt is not None:
        style.font.size = Pt(size_pt)
    if color is not None:
        style.font.color.rgb = color
    if align_center:
        style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    style.paragraph_format.space_after = Pt(6)
    return style


def ensure_report_styles(doc) -> None:
    """
    Make sure the styles the writer names exist on ``doc``. A user template
    that already defines them keeps its own definitions — this only adds
    what is missing, it never restyles.
    """
    _ensure_paragraph_style(doc, DISCLOSURE_STYLE, italic=True, size_pt=9.5,
                            color=_INK_MUTED)
    _ensure_paragraph_style(doc, CAPTION_STYLE, italic=True, size_pt=9,
                            color=_INK_MUTED, align_center=True)


def default_template_document():
    """A fresh Document with the report styles and a generated-by footer."""
    doc = Document()
    ensure_report_styles(doc)
    footer = doc.sections[0].footer
    para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    para.text = "Generated by PyPSA Studio — every figure is computed, not narrated"
    para.style = doc.styles[DISCLOSURE_STYLE]
    return doc
