"""
A FROZEN copy of the two-area kernel as shipped on 2026-09-27 (commit
``efa8abf``) — the oracle the 2026-09-28 work packages are pinned against.

Every later extension (grid storage, several areas, common-mode events)
must leave ``simulate_zonal_blocks`` returning exactly what this function
returns whenever the new feature does not apply. Do not edit this file to
make a test pass; it is the reference, not the implementation.
"""
from __future__ import annotations

import dataclasses

import numpy as np

from services.adequacy.mc import (
    SHORTFALL_TOL,
    _active_storage,
    _dispatch,
    block_store_arrays,
    sample_capacity,
)

GRID_STREAM_KEY = 2**32 - 1


def _ss(seed):
    return seed if isinstance(seed, np.random.SeedSequence) \
        else np.random.SeedSequence(seed)


def _fresh(ss, extra=()):
    return np.random.SeedSequence(ss.entropy, spawn_key=(*ss.spawn_key, *extra),
                                  pool_size=ss.pool_size)


def legacy_zonal_blocks(hub, grid, import_idx, firm_import_mw, delivery_ratio,
                        *, draws, seed, storage_enabled=True,
                        initial_soc_frac=1.0) -> dict:
    residual, weights = hub.residual, hub.weights
    H = residual.size
    ss = _ss(seed)
    units = tuple(hub.units)
    imp = frozenset(int(i) for i in import_idx)
    hub_t = np.ascontiguousarray(sample_capacity(
        units, H, draws, _fresh(ss), exclude=imp, periods=hub.periods).T)
    link_only = tuple(u if i in imp else dataclasses.replace(u, q=0.0)
                      for i, u in enumerate(units))
    link_t = np.ascontiguousarray(sample_capacity(
        link_only, H, draws, _fresh(ss),
        exclude=frozenset(range(len(units))) - imp, periods=hub.periods).T)
    grid_t = np.ascontiguousarray(sample_capacity(
        grid.units, H, draws, _fresh(ss, (GRID_STREAM_KEY,)),
        periods=grid.periods).T)
    firm = np.asarray(firm_import_mw, dtype=np.float64)
    residual_raw = residual + firm
    ratio = np.asarray(delivery_ratio, dtype=np.float64)
    stores = _active_storage(hub, storage_enabled, ())
    any_series = any(getattr(s, "capacity_series", None) is not None
                     for s in stores)
    out = {}
    for label, start, end in hub.periods:
        n_store, p_nom, e_nom, eff_s, eff_d = block_store_arrays(
            stores, start, end, any_series=any_series)
        single = np.zeros((1, draws), dtype=np.intp) if n_store == 1 else None
        lole = np.zeros(draws)
        eue = np.zeros(draws)
        soc = np.repeat((e_nom * float(initial_soc_frac))[:, None], draws,
                        axis=1) if n_store else np.zeros((0, draws))
        for h in range(start, end):
            surplus = np.maximum(
                grid_t[h].astype(np.float64) - grid.residual[h], 0.0) * ratio[h]
            offered = link_t[h].astype(np.float64) + firm[h]
            imp_h = np.minimum(offered, surplus).astype(np.float32)
            deficit = residual_raw[h] - (hub_t[h] + imp_h).astype(np.float64)
            if n_store:
                order = single if n_store == 1 else np.argsort(
                    soc, axis=0, kind="stable")
                deficit = _dispatch(deficit, soc, p_nom, e_nom, eff_s, eff_d,
                                    order)
            lole += weights[h] * (deficit > SHORTFALL_TOL)
            eue += weights[h] * np.maximum(deficit, 0.0)
        out[label] = (lole, eue)
    return out
