from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from db.base import Base
import db.models  # noqa: F401
from settings import get_settings

config = context.config

if (
    config.config_file_name is not None
    and config.attributes.get("configure_logger", "true") != "false"
):
    fileConfig(config.config_file_name)

# Only fall back to settings when the caller did not supply a URL. Without this
# guard, `local_bootstrap.ensure_schema(url)` silently migrates
# `get_settings().database_url` instead of `url` — under pytest that is
# conftest's in-memory database, so the file the caller asked for never gets
# its tables and the failure is invisible.
if not config.attributes.get("explicit_url"):
    config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            # Autogenerate-rendering flag: makes `alembic revision
            # --autogenerate` emit op.batch_alter_table(...), which SQLite needs
            # because it cannot ALTER or DROP COLUMN. It does NOT change how
            # existing migrations execute — 0002 works because its author wrote
            # batch_alter_table by hand. Set here so the next autogenerated
            # migration is SQLite-safe by default.
            #
            # Deliberately NOT set on the offline block above (spec G2 asks for
            # both): that path emits SQL and never autogenerates, so the flag is
            # inert there and would imply a behaviour it does not have.
            render_as_batch=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
